### ISSUE TITLE
SonarCloud quality gate failing

### ISSUE THREAD

**Issue by SarahAlidoost** [hybridlabs-nl/FOWT-ML#19]
The sonarcloud does not calculate the coverage correctly. Perhaps it does not find the path, see https://github.com/marketplace/actions/official-sonarqube-scan

**Comment by SarahAlidoost** [comment]
Solution: the installation should be in editable mode using `-e` for the coverage package to be able to trace the files:

```yaml

      - name: Install dependencies
      # it should be in editable mode for coverage to work
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
      - name: Run unit tests and store coverage
        run: |
          coverage run
          coverage report -m
          coverage xml -o coverage.xml

```



. See this [commit](https://github.com/hybridlabs-nl/FOWT-ML/pull/15/commits/b6e8051edfcca39f67d0da080d45c425c146ee59) for more info.
